[tool.isort]
py_version = 310
profile = "black"
line_length = 88
lines_after_imports = 2
known_first_party = ["entrypoints", "history", "models", "routers", "services", "utilities"]

[tool.mypy]
python_version = "3.10"
plugins = ["pydantic.mypy", "sqlmypy"]
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_redundant_casts = true
