[tool.isort]
py_version = 310
line_length = 88
lines_after_imports = 2
known_first_party = ["apis", "history", "models", "config"]

[tool.mypy]
python_version = "3.10"
plugins = "pydantic.mypy"
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_redundant_casts = true

[[tool.mypy.overrides]]
module = "docker"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pyrate_limiter"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pyyoutube"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "watchdog.events"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "watchdog.observers"
ignore_missing_imports = true
