[tool.isort]
py_version = 3.10
line_length = 88
known_first_party = ["apis", "history", "models", "config"]

[tool.mypy]
python_version = "3.10"

[[tool.mypy.overrides]]
module = "pyyoutube"
ignore_missing_imports = true
